# Generated by Django 3.2.2 on 2022-04-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name=50)),
                ('author', models.TextField(verbose_name=100)),
                ('genre', models.TextField(verbose_name=50)),
                ('date_created', models.DateTimeField()),
                ('content', models.TextField(verbose_name=2000)),
            ],
        ),
    ]
