# Generated by Django 3.2.2 on 2022-04-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tales',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tales',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tales',
            name='genre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tales',
            name='title',
            field=models.TextField(),
        ),
    ]
