# Generated by Django 3.2.2 on 2022-04-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tales',
            name='featured_tale',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
