# Generated by Django 3.2.2 on 2022-04-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0002_tales_featured_tale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tales',
            name='featured_tale',
            field=models.BooleanField(default=True),
        ),
    ]
