# Generated by Django 3.2.2 on 2022-04-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0003_alter_tales_featured_tale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tales',
            name='date_created',
        ),
    ]
